### ISSUE TITLE
Build instructions incorrect

### ISSUE THREAD

**Issue by camopants** [dicekeys/read-dicekey#24]
Instructions for build in README.md:

```
cd read-keysqr
cmake -B build
cd build
make
ctest
```

There is no directory 'read-keysqr'.
There are no 'build' directories in the tree.

**Comment by UppaJung** [comment]
fixed by rename to read-dicekey

**Comment by UppaJung** [comment]
(cmake should create the build directory.  if not, let me know and I'll add mkdir build.)
